// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0N7rTQry-8S_2Zrh-fUxFci-oB_aZ0Q4',
    appId: '1:675446181607:android:371d7d164cef6322d3dc42',
    messagingSenderId: '675446181607',
    projectId: 'food-delivery-da0cd',
    storageBucket: 'food-delivery-da0cd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCj9yBwk5lBJgbRSQYJHIwO6uy17Z-P9Hc',
    appId: '1:675446181607:ios:79c6e92311726f6bd3dc42',
    messagingSenderId: '675446181607',
    projectId: 'food-delivery-da0cd',
    storageBucket: 'food-delivery-da0cd.appspot.com',
    androidClientId: '675446181607-tok3u5b5p985viohoc099ceqpa7lr9hl.apps.googleusercontent.com',
    iosClientId: '675446181607-2slhm63j9nan0co92d3logfltkev09bm.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodDelivery',
  );
}
